# Makefile is only for cleaning - use the setup.py script to build

.PHONY: clean
clean:
	-rm -rf build d3q15/CDelta.py d3q15/CDelta_wrap.c d3q15/CyDelta.c d3q15/CyDelta.so d3q15/_CDelta.so d3q15/_d3q15.so d3q15/_utils.so d3q15/d3q15.py d3q15/d3q15_wrap.c d3q15/eigenvectors.py d3q15/fallers/__helpers.so d3q15/fallers/_helpers.py d3q15/fallers/helpers_wrap.c d3q15/utils.py d3q15/utils_wrap.c
